# Generated by Django 4.2.23 on 2025-07-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='clinic',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='hospital_email',
            field=models.EmailField(help_text='The official email for communication.', max_length=254, unique=True),
        ),
    ]
