# Generated by Django 4.2.23 on 2025-07-13 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external_api', '0002_apikey_clinic_alter_apikey_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='clinic',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'clinic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='hospital_email',
            field=models.EmailField(help_text='The email of the external hospital. It must be unique.', max_length=254, unique=True),
        ),
    ]
