# Generated by Django 5.2.3 on 2025-06-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_user_options_passwordresetotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Password Reset OTPs'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
