# Generated by Django 5.2.3 on 2025-06-18 06:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_passwordresetotp_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(max_length=17)),
                ('reason_for_consultation', models.CharField(choices=[('sperm_donor', 'Sperm Donor Consultation'), ('egg_donor', 'Egg Donor Consultation'), ('surrogate', 'Surrogate Consultation'), ('ivf_treatment', 'IVF Treatment'), ('fertility_assessment', 'Fertility Assessment'), ('genetic_counseling', 'Genetic Counseling'), ('other', 'Other')], default='other', max_length=50)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'user_type': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_appointments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_appointments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['admin', 'subadmin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('instant', 'Instant Meeting'), ('scheduled', 'Scheduled Meeting')], max_length=20)),
                ('meeting_link', models.URLField(max_length=500)),
                ('meeting_id', models.CharField(max_length=100, unique=True)),
                ('passcode', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('creation_email_sent', models.BooleanField(default=False)),
                ('reminder_email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='apis.appointment')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type__in': ['admin', 'subadmin']}, on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'SubAdmin'), ('parent', 'Parent'), ('clinic', 'Clinic')], max_length=20)),
                ('creation_email_sent', models.BooleanField(default=False)),
                ('creation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_email_sent', models.BooleanField(default=False)),
                ('reminder_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='apis.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_participants',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
