# Generated by Django 4.2.23 on 2025-06-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_subscriptionplan_billing_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=17)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('donor_type', models.CharField(choices=[('sperm', 'Sperm Donor'), ('egg', 'Egg Donor'), ('embryo', 'Embryo Donor')], max_length=20)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending Verification'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('eye_color', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=50, null=True)),
                ('skin_tone', models.CharField(blank=True, max_length=50, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Degree')], max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('genetic_conditions', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('smoking_status', models.BooleanField(default=False)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=50, null=True)),
                ('exercise_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('family_medical_history', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='donor_profiles/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='donor_documents/')),
                ('personality_traits', models.JSONField(blank=True, default=dict)),
                ('interests_hobbies', models.JSONField(blank=True, default=list)),
                ('ai_matching_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(limit_choices_to={'user_type': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_donors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='donor_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apis.donor')),
            ],
            options={
                'db_table': 'donor_images',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Document'), ('medical', 'Medical Report'), ('education', 'Education Certificate'), ('screening', 'Screening Report'), ('consent', 'Consent Form'), ('other', 'Other')], max_length=20)),
                ('document', models.FileField(upload_to='donor_documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_files', to='apis.donor')),
            ],
            options={
                'db_table': 'donor_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['donor_type', 'availability_status'], name='donors_donor_t_a75f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['clinic', 'is_active'], name='donors_clinic__2d724a_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['blood_group'], name='donors_blood_g_d4753e_idx'),
        ),
        migrations.AddIndex(
            model_name='donor',
            index=models.Index(fields=['location'], name='donors_locatio_10a11b_idx'),
        ),
    ]
