# Generated by Django 4.2.23 on 2025-06-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_donor_donorimage_donordocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.donor'),
        ),
    ]
