# Generated by Django 4.2.23 on 2025-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_user_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('pending', 'Pending Verification'), ('suspended', 'Suspended')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('sperm', 'Sperm Donor'), ('egg', 'Egg Donor'), ('embryo', 'Embryo Donor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donor',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Degree')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
