# Generated by Django 4.2.23 on 2025-06-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_donor_availability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_type_preference', models.CharField(choices=[('sperm', 'Sperm Donor'), ('egg', 'Egg Donor'), ('both', 'Both')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('preferred_height_min', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('preferred_height_max', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('preferred_ethnicity', models.CharField(blank=True, choices=[('caucasian', 'Caucasian'), ('african', 'African'), ('asian', 'Asian'), ('hispanic', 'Hispanic'), ('middle_eastern', 'Middle Eastern'), ('mixed', 'Mixed'), ('other', 'Other')], max_length=50)),
                ('preferred_eye_color', models.CharField(blank=True, choices=[('brown', 'Brown'), ('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel'), ('gray', 'Gray')], max_length=20)),
                ('preferred_hair_color', models.CharField(blank=True, max_length=50)),
                ('preferred_education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('doctorate', 'Doctorate'), ('professional', 'Professional Degree')], max_length=50)),
                ('genetic_screening_required', models.BooleanField(default=True)),
                ('preferred_age_min', models.IntegerField(blank=True, null=True)),
                ('preferred_age_max', models.IntegerField(blank=True, null=True)),
                ('preferred_occupation', models.CharField(blank=True, max_length=255)),
                ('preferred_religion', models.CharField(blank=True, max_length=100)),
                ('importance_physical', models.IntegerField(default=5, help_text='1-10 scale')),
                ('importance_education', models.IntegerField(default=5, help_text='1-10 scale')),
                ('importance_medical', models.IntegerField(default=5, help_text='1-10 scale')),
                ('importance_personality', models.IntegerField(default=5, help_text='1-10 scale')),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertility_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fertility_profiles',
                'unique_together': {('parent', 'donor_type_preference')},
            },
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_id', models.CharField(max_length=255)),
                ('clinic_id', models.UUIDField()),
                ('match_score', models.FloatField()),
                ('matched_attributes', models.JSONField()),
                ('ai_explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fertility_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.fertilityprofile')),
            ],
            options={
                'db_table': 'matching_results',
                'unique_together': {('fertility_profile', 'donor_id')},
            },
        ),
    ]
