# Generated by Django 4.2.23 on 2025-07-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text="Permissions for subadmin users. Format: {'clinic': True, 'parent': False, ...}"),
        ),
    ]
