# Generated by Django 4.2.23 on 2025-07-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_fertilityprofile_matchingresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='education_level',
            field=models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Degree')], max_length=50, null=True),
        ),
    ]
