# Generated by Django 4.2.23 on 2025-07-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_user_permissions_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=25),
        ),
    ]
