# Generated by Django 4.2.23 on 2025-07-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_donor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='The ID of the corresponding price object in Stripe.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for this user.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='The ID of the subscription in Stripe.', max_length=255, null=True, unique=True),
        ),
    ]
