# Generated by Django 4.2.23 on 2025-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=20),
        ),
    ]
