# Generated by Django 4.2.23 on 2025-07-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_alter_subscriptionplan_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='needs_embedding_update',
            field=models.BooleanField(default=False, help_text='Flag to indicate if embedding needs update'),
        ),
    ]
