# Generated by Django 4.2.23 on 2025-07-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_alter_subscriptionplan_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_type',
            field=models.CharField(choices=[('sperm', 'Sperm Donor'), ('egg', 'Egg Donor'), ('surrogate', 'Surrogate Donor')], max_length=50),
        ),
    ]
