# Generated by Django 4.2.23 on 2025-07-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_blogmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='completion_notes',
            field=models.TextField(blank=True, help_text='Notes added when meeting is completed', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the meeting', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_for_consultation',
            field=models.CharField(choices=[('sperm', 'Sperm Donor Consultation'), ('egg', 'Egg Donor Consultation'), ('surrogate', 'Surrogate Consultation')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
    ]
