# Generated by Django 4.2.23 on 2025-07-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_meeting_completion_notes_meeting_meeting_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='cancellation_notes',
            field=models.TextField(blank=True, help_text='Reason for cancellation', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='confirmation_notes',
            field=models.TextField(blank=True, help_text='Notes added when appointment is confirmed', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reschedule_notes',
            field=models.TextField(blank=True, help_text='Notes about rescheduling', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status_change_notes',
            field=models.TextField(blank=True, help_text='Notes added when status is changed', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changed_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_notes',
            field=models.TextField(blank=True, help_text='General admin notes about the meeting', null=True),
        ),
    ]
