version: "3.9"

services:
  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    command: gunicorn embryva_backend.wsgi:application --bind 0.0.0.0:8080 --workers 3 --timeout 120
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: embryva_backend.settings
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always

  worker:
    build: .
    command: celery -A embryva_backend worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: embryva_backend.settings
    depends_on:
      - redis
    restart: unless-stopped

  beat:
    build: .
    command: >
      celery -A embryva_backend beat
      --loglevel=info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: embryva_backend.settings
    depends_on:
      - redis
    restart: unless-stopped